language: ruby
services:
  - docker
script:
  - cd docker
  - bash generate.sh -v $BUILD_EVM_VERSION
env:
  # - BUILD_EVM_VERSION=24.1
  # - BUILD_EVM_VERSION=24.2
  # - BUILD_EVM_VERSION=24.3
  # - BUILD_EVM_VERSION=24.4
  # - BUILD_EVM_VERSION=24.5
  # - BUILD_EVM_VERSION=25.1
  # - BUILD_EVM_VERSION=25.2
  # - BUILD_EVM_VERSION=25.3
  # - BUILD_EVM_VERSION=26.1
  - BUILD_EVM_VERSION=git-snapshot
