language: ruby
addons:
  apt:
    packages:
      - autoconf
      - autogen
      - automake
      - build-essential
      - git
      - libncurses5-dev
      - libtool
      - texinfo
script:
  - cd docker
  - bash build-emacs.sh
env:
  - VERSION=24.1
  - VERSION=24.2
  - VERSION=24.3
  - VERSION=24.4
  - VERSION=24.5
  - VERSION=25.1
  - VERSION=25.2
  - VERSION=25.3
  - VERSION=26.1
  - VERSION=git-snapshot
